<?php /** @var T4webPermissions\Controller\Admin\RolesViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-key"></i> Permissions. Roles</h1>
</section>

<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Roles</h3>
            <div class="box-tools">
                <a href="/employee/add" class="btn btn-labeled btn-primary btn-sm" style="width: 100%;">
                    <i class="btn-label fa fa-plus"></i> Add employee
                </a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
            <table class="table">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Name</th>
                    <th style="width: 200px">Actions</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Update software</td>
                    <td>
                        <a href="/employee/add" class="btn btn-labeled btn-primary btn-sm" style="width: 100%;">
                            <i class="btn-label fa fa-plus"></i> Edit
                        </a>
                        <a href="/employee/add" class="btn btn-labeled btn-primary btn-sm" style="width: 100%;">
                            <i class="btn-label fa fa-plus"></i> Delete
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Clean database</td>
                    <td>Clean database</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Cron job running</td>
                    <td>Cron job running</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Fix and squish bugs</td>
                    <td>Fix and squish bugs</td>
                </tr>
            </table>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
            <ul class="pagination no-margin">
                <li class="disabled"><a href="#">«</a></li>
                <li class="disabled"><a href="#">1</a></li>
                <li class="disabled"><a href="#">»</a></li>
            </ul>
        </div>
    </div>

</section>