<?php /** @var T4webPermissions\Controller\Admin\RolesViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-key"></i> Permissions. Roles</h1>
</section>

<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
    </div>

</section>