<?php /** @var T4webPermissions\Controller\Admin\RolesViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-key"></i> Permissions. Roles</h1>
</section>

<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Roles</h3>
            <div class="box-tools">
                <a href="<?=$this->url('admin-permissions-roles-add')?>" class="btn btn-labeled btn-primary btn-sm">
                    <i class="btn-label fa fa-plus"></i> Add role
                </a>
            </div>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
            <table class="table">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Name</th>
                    <th style="width: 200px">Permissions</th>
                    <th style="width: 200px">Actions</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Administrators</td>
                    <td><a href="<?=$this->url('admin-permissions-roles-permissions', ['id' => 1])?>" >Show permissions</a>
                    </td>
                    <td>
                        <a href="<?=$this->url('admin-permissions-roles-edit', ['id' => 1])?>" class="btn btn-warning btn-xs" >
                            <i class="fa fa-pencil"></i> Edit
                        </a>
                        <a href="<?=$this->url('admin-permissions-roles-delete', ['id' => 1])?>" class="btn btn-danger btn-xs" >
                            <i class="fa fa-times"></i> Delete
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Users</td>
                    <td><a href="<?=$this->url('admin-permissions-roles-permissions', ['id' => 1])?>" >Show permissions</a>
                    <td>
                        <a href="<?=$this->url('admin-permissions-roles-edit', ['id' => 1])?>" class="btn btn-warning btn-xs" >
                            <i class="fa fa-pencil"></i> Edit
                        </a>
                        <a href="<?=$this->url('admin-permissions-roles-delete', ['id' => 1])?>" class="btn btn-danger btn-xs" >
                            <i class="fa fa-times"></i> Delete
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Moderators</td>
                    <td><a href="<?=$this->url('admin-permissions-roles-permissions', ['id' => 1])?>" >Show permissions</a>
                    <td>
                        <a href="<?=$this->url('admin-permissions-roles-edit', ['id' => 1])?>" class="btn btn-warning btn-xs" >
                            <i class="fa fa-pencil"></i> Edit
                        </a>
                        <a href="<?=$this->url('admin-permissions-roles-delete', ['id' => 1])?>" class="btn btn-danger btn-xs" >
                            <i class="fa fa-times"></i> Delete
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Translators</td>
                    <td><a href="<?=$this->url('admin-permissions-roles-permissions', ['id' => 1])?>" >Show permissions</a>
                    <td>
                        <a href="<?=$this->url('admin-permissions-roles-edit', ['id' => 1])?>" class="btn btn-warning btn-xs" >
                            <i class="fa fa-pencil"></i> Edit
                        </a>
                        <a href="<?=$this->url('admin-permissions-roles-delete', ['id' => 1])?>" class="btn btn-danger btn-xs" >
                            <i class="fa fa-times"></i> Delete
                        </a>
                    </td>
                </tr>
            </table>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
            <ul class="pagination no-margin">
                <li class="disabled"><a href="#">«</a></li>
                <li class="disabled"><a href="#">1</a></li>
                <li class="disabled"><a href="#">»</a></li>
            </ul>
        </div>
    </div>

</section>