<?php /** @var T4webPermissions\Controller\Admin\RolesViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-key"></i> Permissions. Administrators permissions</h1>
</section>

<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Permissions group 1</h3>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
            <table class="table">
                <tr>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                </tr>
            </table>
        </div><!-- /.box-body -->

        <div class="box-header">
            <h3 class="box-title">Permissions group 2</h3>
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
            <table class="table">
                <tr>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                    <td>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox">
                                Privilege 1
                            </label>
                        </div>
                    </td>
                </tr>
            </table>
        </div><!-- /.box-body -->
        <div class="box-footer clearfix">
            <button class="btn btn-primary" type="submit">Save</button>
            <a href="<?=$this->url('admin-permissions-roles-list')?>" class="btn btn-default" >Cancel and return to roles</a>
        </div>
    </div>

</section>