<?php /** @var T4webPermissions\Controller\Admin\RolesViewModel $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<section class="content-header">
    <h1><i class="fa fa-key"></i> Permissions. Create role</h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Role</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <form role="form">
                        <!-- text input -->
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" placeholder="Enter name" class="form-control">
                        </div>
                    </form>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button class="btn btn-primary" type="submit">Create</button>
                    <a href="<?=$this->url('admin-permissions-roles-list')?>" class="btn btn-default" >Cancel and return to roles</a>
                </div>
            </div>
        </div>
    </div>

</section>